SCHEMA_VERSION="OPM-001"
MISSION="independent reality -> future Kalshi price path"
HORIZONS_SECONDS=(5,15,30,60,120,300)
PROBABILITY_ENABLED=False
DIRECTION_ENABLED=False
PUBLICATION_ALLOWED=False
EXECUTION_AUTHORITY=False
