from pathlib import Path
import shutil

R = Path.cwd()
P = R / "qseries_v2" / "oracle_predictive_discovery" / "opd_live_full_evidence_fusion_predictor.py"
T = R / "test_opd_LIVE_FULL_EVIDENCE_FRESH_CANONICAL_CUTOVER_REBUILD.py"
B = P.with_suffix(".pre_fresh_canonical_cutover_rebuild.bak")

MODULE_LINES = [
    'from pathlib import Path\n',
    'import json,time\n',
    '\n',
    'from qseries_v2.oracle_production_hardening.oph_019_postgresql_universal_ingestion_queue import connect\n',
    'from qseries_v2.oracle_predictive_discovery.opd_046_exact_kalshi_future_price_materializer import canonical_point,SOURCE\n',
    'from qseries_v2.oracle_predictive_discovery.opd_062_strict_asof_live_world_state import assemble\n',
    'from qseries_v2.oracle_predictive_discovery.opd_041_exact_live_token_materializer import materialize_exact_live_tokens\n',
    '\n',
    'EXECUTION_AUTHORITY=False\n',
    'PUBLICATION_ALLOWED=False\n',
    'HURDLE=0.020\n',
    'MIN_NET_EDGE=0.005\n',
    'MIN_CASES=20\n',
    'MIN_TICKERS=3\n',
    'MIN_DIRECTION_PROB=0.58\n',
    'MIN_MEAN_SIMILARITY=0.20\n',
    'MAX_STATE_AGE_SECONDS=120.0\n',
    'MAX_NEIGHBORS=100\n',
    'CATEGORIES=("K","CB","CC","L")\n',
    'HORIZONS=(5,15,30,60,300,900,3600)\n',
    '\n',
    'def _rows(p):\n',
    '    out=[]\n',
    '    if not p.exists(): return out\n',
    '    with p.open(encoding="utf-8") as f:\n',
    '        for line in f:\n',
    '            if not line.strip(): continue\n',
    '            try: out.append(json.loads(line))\n',
    '            except Exception: pass\n',
    '    return out\n',
    '\n',
    'def _asset(ticker):\n',
    '    u=str(ticker).upper()\n',
    '    if "BTC" in u:return "BTC"\n',
    '    if "ETH" in u:return "ETH"\n',
    '    if "SOL" in u:return "SOL"\n',
    '    return None\n',
    '\n',
    'def _cats(tokens):\n',
    '    d={k:set() for k in CATEGORIES}\n',
    '    for x in tokens or []:\n',
    '        s=str(x)\n',
    '        if ":" not in s: continue\n',
    '        p=s.split(":",1)[0]\n',
    '        if p in d:d[p].add(s)\n',
    '    return d\n',
    '\n',
    'def _jaccard(a,b):\n',
    '    if not a and not b:return None\n',
    '    u=a|b\n',
    '    return len(a&b)/len(u) if u else None\n',
    '\n',
    'def _similarity(a,b):\n',
    '    ca,cb=_cats(a),_cats(b); vals=[]\n',
    '    for k in CATEGORIES:\n',
    '        if ca[k]:\n',
    '            z=_jaccard(ca[k],cb[k])\n',
    '            if z is not None: vals.append(z)\n',
    '    return sum(vals)/len(vals) if vals else 0.0\n',
    '\n',
    'def _weighted_mean(pairs):\n',
    '    sw=sum(w for w,_ in pairs)\n',
    '    return None if sw<=0 else sum(w*x for w,x in pairs)/sw\n',
    '\n',
    'def _anchor_from_row(row):\n',
    '    seq,oid,outer_epoch,obj=row\n',
    '    p=canonical_point(obj,float(outer_epoch))\n',
    '    if not p:return None\n',
    '    asset=_asset(p["ticker"])\n',
    '    if not asset:return None\n',
    '    return {\n',
    '      "anchor_id":str(oid),"ticker":p["ticker"],"asset":asset,\n',
    '      "observed_epoch":float(p["event_epoch"]),"anchor_price":float(p["price"]),\n',
    '      "anchor_sequence_boundary":int(seq),"anchor_sequence_basis":"EXACT_CANONICAL_OBSERVATION",\n',
    '      "kalshi_state":{"sequence_number":int(seq),"event_epoch":float(p["event_epoch"]),\n',
    '        "trade_price":float(p["price"]),"yes_bid":None,"yes_ask":None,"spread":None,\n',
    '        "yes_bid_size":None,"yes_ask_size":None,"last_trade_size":None,"volume":None,\n',
    '        "open_interest":None,"observation_type":"canonical_market_data",\n',
    '        "event_time_path":"OPD046_CANONICAL_POINT"},"post_freeze":True,\n',
    '    }\n',
    '\n',
    'def latest_live_anchor(root):\n',
    "    sql='''SELECT sequence_number,observation_id,EXTRACT(EPOCH FROM observed_at),canonical_observation_json\n",
    '           FROM public.oracle_canonical_observations\n',
    '           WHERE source_id=%s\n',
    "             AND ((canonical_observation_json->'payload'->>'source_market_id') ILIKE '%%BTC%%'\n",
    "               OR (canonical_observation_json->'payload'->>'source_market_id') ILIKE '%%ETH%%'\n",
    "               OR (canonical_observation_json->'payload'->>'source_market_id') ILIKE '%%SOL%%')\n",
    "           ORDER BY sequence_number DESC LIMIT 64'''\n",
    '    with connect(root,autocommit=False) as c:\n',
    '        with c.cursor() as q:\n',
    '            q.execute("SET TRANSACTION READ ONLY")\n',
    '            q.execute("SET LOCAL statement_timeout=\'5000ms\'")\n',
    '            q.execute(sql,(SOURCE,)); rows=q.fetchall() or []\n',
    '        c.rollback()\n',
    '    for row in rows:\n',
    '        a=_anchor_from_row(row)\n',
    '        if a:return a\n',
    '    return None\n',
    '\n',
    'def materialize_current_states(anchor,root):\n',
    '    extra=assemble(anchor,root); out=[]\n',
    '    for h in HORIZONS:\n',
    '        world={"anchor_id":anchor["anchor_id"],"ticker":anchor["ticker"],\n',
    '          "observed_epoch":anchor["observed_epoch"],"horizon_seconds":h,\n',
    '          "anchor_price":anchor["anchor_price"],"kalshi_state":anchor["kalshi_state"],\n',
    '          "coinbase_hf_state":extra["coinbase_hf_state"],\n',
    '          "crypto_condition_state":extra["crypto_condition_state"],\n',
    '          "learned_state":extra["learned_state"]}\n',
    '        out.append({"state_id":"LIVE_IN_MEMORY_"+anchor["anchor_id"]+"_"+str(h),\n',
    '          "anchor_id":anchor["anchor_id"],"ticker":anchor["ticker"],\n',
    '          "observed_epoch":float(anchor["observed_epoch"]),"horizon_seconds":h,\n',
    '          "anchor_price":anchor["anchor_price"],"tokens":list(materialize_exact_live_tokens(root,world))})\n',
    '    return out,extra\n',
    '\n',
    'def _score_state(cur,states,outcomes,now):\n',
    '    h=int(cur["horizon_seconds"]); asset=_asset(cur.get("ticker"));t=float(cur["observed_epoch"]);hist=[]\n',
    '    for s in states:\n',
    '        if s.get("state_id")==cur.get("state_id") or int(s.get("horizon_seconds",-1))!=h:continue\n',
    '        if asset and _asset(s.get("ticker"))!=asset:continue\n',
    '        if float(s.get("observed_epoch",0))>=t:continue\n',
    '        o=outcomes.get(s.get("state_id"))\n',
    '        if not o or float(o.get("resolution_epoch",1e99))>t:continue\n',
    '        sim=_similarity(cur.get("tokens") or [],s.get("tokens") or [])\n',
    '        if sim<=0:continue\n',
    '        try:r=float(o["future_return"]);mfe=float(o["mfe"]);mae=float(o["mae"])\n',
    '        except Exception:continue\n',
    '        hist.append((sim,s,o,r,mfe,mae))\n',
    '    hist.sort(key=lambda z:(z[0],float(z[1].get("observed_epoch",0))),reverse=True);hist=hist[:MAX_NEIGHBORS]\n',
    '    n=len(hist);tickers=len({x[1].get("ticker") for x in hist});mean_sim=sum(x[0] for x in hist)/n if n else 0.0\n',
    '    mean_ret=_weighted_mean([(x[0],x[3]) for x in hist])\n',
    '    if hist:\n',
    '        sw=sum(x[0] for x in hist);up_prob=sum(x[0]*(1.0 if x[3]>0 else .5 if x[3]==0 else 0.0) for x in hist)/sw\n',
    '        mean_mfe=sum(x[0]*x[4] for x in hist)/sw;mean_mae=sum(x[0]*x[5] for x in hist)/sw\n',
    '    else:up_prob=mean_mfe=mean_mae=None\n',
    '    direction=prob=None\n',
    '    if up_prob is not None:\n',
    '        direction="UP" if up_prob>=.5 else "DOWN";prob=up_prob if direction=="UP" else 1.0-up_prob\n',
    '    directional_return=None if mean_ret is None else (mean_ret if direction=="UP" else -mean_ret)\n',
    '    net=None if directional_return is None else directional_return-HURDLE\n',
    '    curcats=_cats(cur.get("tokens") or []);votes={}\n',
    '    for k in CATEGORIES:\n',
    '        if not curcats[k]:continue\n',
    '        pairs=[]\n',
    '        for _,s,o,r,_,_ in hist:\n',
    '            z=_jaccard(curcats[k],_cats(s.get("tokens") or [])[k])\n',
    '            if z and z>0:pairs.append((z,r))\n',
    '        m=_weighted_mean(pairs);votes[k]={"cases":len(pairs),"mean_return":m,"direction":None if m is None or abs(m)<1e-12 else ("UP" if m>0 else "DOWN")}\n',
    '    directional_votes=[v["direction"] for v in votes.values() if v["direction"]]\n',
    '    agree=(sum(v==direction for v in directional_votes)/len(directional_votes)) if direction and directional_votes else None\n',
    '    age=max(0.0,float(now)-t)\n',
    '    checks={"fresh_state":age<=MAX_STATE_AGE_SECONDS,"comparable_cases":n>=MIN_CASES,\n',
    '      "ticker_breadth":tickers>=MIN_TICKERS,"mean_similarity":mean_sim>=MIN_MEAN_SIMILARITY,\n',
    '      "direction_probability":prob is not None and prob>=MIN_DIRECTION_PROB,\n',
    '      "net_edge":net is not None and net>=MIN_NET_EDGE,\n',
    '      "evidence_agreement":agree is not None and len(directional_votes)>=2 and agree>=0.60}\n',
    '    return {"state":cur,"asset":asset,"horizon_seconds":h,"age_seconds":age,"comparable_cases":n,\n',
    '      "unique_tickers":tickers,"mean_similarity":mean_sim,"direction":direction,"predicted_probability":prob,\n',
    '      "expected_return":directional_return,"net_edge_after_2pct":net,"expected_mfe":mean_mfe,"expected_mae":mean_mae,\n',
    '      "evidence_votes":votes,"evidence_agreement":agree,"checks":checks,"passed":all(checks.values())}\n',
    '\n',
    'def run(root=None,now=None,anchor=None):\n',
    '    root=Path(root or Path.cwd()).resolve();now=float(time.time() if now is None else now);rt=root/"runtime"/"predictive_data"\n',
    '    history=_rows(rt/"opd_032_prospective_state_ledger.jsonl")\n',
    '    outcomes={x.get("state_id"):x for x in _rows(rt/"opd_033_prospective_outcome_ledger.jsonl")}\n',
    '    print("="*112);print("ORACLE LIVE FULL-EVIDENCE FUSION PREDICTOR — FRESH CANONICAL CUTOVER");print("="*112)\n',
    '    anchor=anchor or latest_live_anchor(root)\n',
    '    if not anchor:\n',
    '        print("LIVE_PREDICTION=ABSTAIN");print("REASON=NO_LIVE_CANONICAL_CRYPTO_ANCHOR");print("EXECUTION_AUTHORITY=FALSE");return None\n',
    '    print("LIVE_ANCHOR_TICKER=",anchor["ticker"]);print("LIVE_ANCHOR_SEQUENCE=",anchor.get("anchor_sequence_boundary"))\n',
    '    print("LIVE_ANCHOR_AGE_SECONDS=",max(0.0,now-float(anchor["observed_epoch"])))\n',
    '    current,extra=materialize_current_states(anchor,root)\n',
    '    print("LIVE_EVIDENCE_COINBASE_WINDOWS=",sorted(extra["coinbase_hf_state"].keys()))\n',
    '    print("LIVE_EVIDENCE_CONDITION_METRICS=",len(extra["crypto_condition_state"]));print("LIVE_EVIDENCE_LEARNED=",bool(extra["learned_state"]))\n',
    '    scores=[_score_state(x,history,outcomes,now) for x in current]\n',
    '    for z in scores:\n',
    '        print("-"*112);print("TICKER=",z["state"]["ticker"],"HORIZON=",z["horizon_seconds"],"AGE_SECONDS=",round(z["age_seconds"],3))\n',
    '        print("EVIDENCE_TOKENS=",len(z["state"].get("tokens") or []),"K/CB/CC/L=",{k:len(_cats(z["state"].get("tokens") or [])[k]) for k in CATEGORIES})\n',
    '        print("COMPARABLE_CASES=",z["comparable_cases"],"UNIQUE_TICKERS=",z["unique_tickers"],"MEAN_SIMILARITY=",round(z["mean_similarity"],6))\n',
    '        print("EVIDENCE_VOTES=",json.dumps(z["evidence_votes"],sort_keys=True,separators=(",",":")));print("EVIDENCE_AGREEMENT=",z["evidence_agreement"])\n',
    '        print("DIRECTION=",z["direction"],"PREDICTED_PROBABILITY=",z["predicted_probability"]);print("EXPECTED_RETURN=",z["expected_return"],"NET_EDGE_AFTER_2PCT=",z["net_edge_after_2pct"])\n',
    '        failed=[k for k,v in z["checks"].items() if not v];print("DECISION="+(z["direction"] if z["passed"] else "ABSTAIN"),"FAILED_GATES="+("NONE" if not failed else ",".join(failed)))\n',
    '    passed=[z for z in scores if z["passed"]];print("="*112)\n',
    '    if passed:\n',
    '        best=max(passed,key=lambda z:(float(z["net_edge_after_2pct"]),float(z["predicted_probability"])))\n',
    '        print("LIVE_PREDICTION=",best["direction"]);print("TICKER=",best["state"]["ticker"]);print("HORIZON_SECONDS=",best["horizon_seconds"])\n',
    '        print("PREDICTED_PROBABILITY=",best["predicted_probability"]);print("EXPECTED_RETURN=",best["expected_return"]);print("NET_EXPECTED_EDGE_AFTER_2PCT=",best["net_edge_after_2pct"])\n',
    '        print("COMPARABLE_CASES=",best["comparable_cases"]);print("UNIQUE_TICKERS=",best["unique_tickers"]);print("EVIDENCE_AGREEMENT=",best["evidence_agreement"]);print("PROFITABILITY_STATUS=LIVE_CANDIDATE_UNPROVEN")\n',
    '    else:\n',
    '        print("LIVE_PREDICTION=ABSTAIN");print("REASON=NO_HORIZON_PASSES_FULL_EVIDENCE_LIVE_DECISION_GATES")\n',
    '    print("CERTIFIED=FALSE");print("PUBLICATION_ALLOWED=FALSE");print("EXECUTION_AUTHORITY=FALSE");return scores\n',
    '\n',
    'if __name__=="__main__":run()\n',
]
MODULE = "".join(MODULE_LINES)

TEST_LINES = [
    'import qseries_v2.oracle_predictive_discovery.opd_live_full_evidence_fusion_predictor as m\n',
    '\n',
    'obj={"payload":{"source_market_id":"KXETH15M-TEST","message":{"market_ticker":"KXETH15M-TEST","price_dollars":"0.42","ts":2000.0}}}\n',
    'a=m._anchor_from_row((77,"obs77",2000.0,obj))\n',
    'assert a and a["ticker"]=="KXETH15M-TEST" and a["asset"]=="ETH"\n',
    'assert a["anchor_sequence_boundary"]==77 and a["anchor_id"]=="obs77" and a["observed_epoch"]==2000.0\n',
    '\n',
    'states=[];outs={}\n',
    'for i in range(24):\n',
    '    sid="h"+str(i);states.append({"state_id":sid,"ticker":"KXETH"+str(i%4),"observed_epoch":1000+i,"horizon_seconds":900,"tokens":["K:A","CB:B","CC:C","L:D"]})\n',
    '    outs[sid]={"state_id":sid,"resolution_epoch":1500+i,"future_return":-0.05,"mfe":-0.01,"mae":-0.05}\n',
    'cur={"state_id":"LIVE","ticker":"KXETH-LIVE","observed_epoch":2000.0,"horizon_seconds":900,"tokens":["K:A","CB:B","CC:C","L:D"]}\n',
    'z=m._score_state(cur,states,outs,2001.0)\n',
    'assert z["passed"] is True and z["direction"]=="DOWN" and z["predicted_probability"]==1.0 and z["net_edge_after_2pct"]>0\n',
    'assert m.EXECUTION_AUTHORITY is False and m.PUBLICATION_ALLOWED is False\n',
    'print("[PASS] exact canonical crypto row becomes an in-memory live anchor")\n',
    'print("[PASS] scorer excludes future/unresolved evidence and preserves full decision gates")\n',
    'print("[PASS] fresh full-evidence DOWN fixture clears support/breadth/probability/economic gates")\n',
    'print("[EXECUTION/PUBLICATION] FALSE/FALSE")\n',
]
TEST = "".join(TEST_LINES)

if not P.exists():
    raise SystemExit("[FAIL] existing predictor missing: " + str(P))
if not B.exists():
    shutil.copy2(P, B)
P.write_text(MODULE, encoding="utf-8")
T.write_text(TEST, encoding="utf-8")
compile(P.read_text(encoding="utf-8"), str(P), "exec")
compile(T.read_text(encoding="utf-8"), str(T), "exec")
print("[PASS] existing full-evidence predictor cut over to exact freshest canonical BTC/ETH/SOL state")
print("[PASS] current forecast no longer comes from newest OPD-032 ledger state")
print("[PASS] historical comparison/outcomes remain existing OPD-032/033 prospective evidence")
print("[EXECUTION/PUBLICATION] FALSE/FALSE")
