from pathlib import Path
import ast,importlib,os,subprocess,sys
ROOT=Path.cwd().resolve();PKG=ROOT/"qseries_v2"/"oracle_intelligence_analytics_runtime";MOD=PKG/"oiar_040_trader_opportunity_time_filter.py";TEST=ROOT/"test_oiar_040_trader_opportunity_time_filter.py";MODULE_SOURCE='from pathlib import Path\nfrom .oiar_025_fast_persisted_trader_brief_read_model import read_fast_trader_brief\nfrom .oiar_039_trader_temporal_classification import build_temporal_map\nOIAR_040_BUILD_ID="OIAR-040";EXECUTION_AUTHORITY=False\ndef requested_window(query):\n q=" ".join(str(query).lower().split())\n if "tonight" in q or "this evening" in q:return "TONIGHT"\n if "today" in q:return "TODAY"\n if "tomorrow" in q:return "TOMORROW"\n if "upcoming" in q:return "UPCOMING"\n return None\ndef read_time_filtered_trader_brief(root=None,query="",limit=20):\n root=Path(root or Path.cwd()).resolve();x=read_fast_trader_brief(root,50);tm=build_temporal_map(root);want=requested_window(query);rows=[]\n for raw in x.markets:\n  r=dict(raw);t=tm.get(str(r.get("market_id")),{"label":"UNKNOWN","proven":False,"event_time":None});r["time_relevance"]=t\n  if want=="TODAY" and t["label"] not in ("TODAY","TONIGHT"):continue\n  if want and want!="TODAY" and t["label"]!=want:continue\n  rows.append(r)\n return tuple(rows[:max(1,min(int(limit),50))])\ndef physical_probe(root=None):\n a=read_time_filtered_trader_brief(root,"",50);b=read_time_filtered_trader_brief(root,"plays for today",50)\n return {"all_markets":len(a),"today_markets":len(b),"unknown_all":sum(r["time_relevance"]["label"]=="UNKNOWN" for r in a),"execution_authority":False}\n';TEST_SOURCE='import unittest,inspect\nimport qseries_v2.oracle_intelligence_analytics_runtime.oiar_040_trader_opportunity_time_filter as m\nclass T(unittest.TestCase):\n def test_identity(self):self.assertEqual(m.OIAR_040_BUILD_ID,"OIAR-040")\n def test_intent(self):self.assertEqual(m.requested_window("plays for today"),"TODAY");self.assertEqual(m.requested_window("this evening"),"TONIGHT")\n def test_no_scan(self):self.assertNotIn("oracle_canonical_observations",inspect.getsource(m))\nif __name__=="__main__":\n print("="*88);print(" OIAR-040 CERTIFICATION TEST");print(" TRADER OPPORTUNITY TIME FILTERING");print("="*88)\n r=unittest.TextTestRunner(verbosity=2).run(unittest.defaultTestLoader.loadTestsFromTestCase(T))\n if not r.wasSuccessful():raise SystemExit(1)\n print("[PASS] requested time window filters snapshot markets")\n';REQUIRED=('qseries_v2/oracle_intelligence_analytics_runtime/oiar_025_fast_persisted_trader_brief_read_model.py', 'qseries_v2/oracle_intelligence_analytics_runtime/oiar_039_trader_temporal_classification.py')
def w(p,s):
 p.parent.mkdir(parents=True,exist_ok=True);t=p.with_name(p.name+f".{os.getpid()}.tmp");t.write_text(s,encoding="utf-8");os.replace(t,p)
def main():
 print("="*88);print(" OIAR-040 INSTALLER");print(" TRADER OPPORTUNITY TIME FILTERING");print("="*88);print("[ROOT]",ROOT)
 for r in REQUIRED:
  if not (ROOT/r).is_file():raise RuntimeError(f"Required proven upstream missing: {ROOT/r}")
 ast.parse(MODULE_SOURCE);ast.parse(TEST_SOURCE);print("[PASS] installer payload syntax verified");w(MOD,MODULE_SOURCE);w(TEST,TEST_SOURCE);subprocess.run([sys.executable,str(TEST)],cwd=str(ROOT),check=True,timeout=30);importlib.invalidate_caches();m=importlib.import_module("qseries_v2.oracle_intelligence_analytics_runtime.oiar_040_trader_opportunity_time_filter");print("[PHYSICAL]",m.physical_probe(ROOT));print("[PASS] snapshot-only filtering preserved");print("[PASS] execution_authority=FALSE");print("[DONE] OIAR-040 INSTALLATION COMPLETE")
if __name__=="__main__":main()
