from pathlib import Path
import py_compile
R=Path.cwd();S=R/"qseries_v2/oracle_strategy_intelligence/solana_money/qarb_clean_bot"
D=S/"qarb_028b_mriya_executor_flow_decoder.py"
if not D.is_file():raise SystemExit("[FAIL] dependency missing: "+str(D))
M=S/"qarb_029b_mriya_real_hotset_coverage_gap.py";M.write_text('from __future__ import annotations\nimport json\nfrom pathlib import Path\nSRC=Path("runtime_state/qseries/qarb_clean_bot/mriya_route_decode.json")\nOUT=Path("runtime_state/qseries/qarb_clean_bot/mriya_hotset_coverage_gap.json")\nWSOL="So11111111111111111111111111111111111111112"\ndef inspect(root):\n    if not SRC.is_file():raise SystemExit("[FAIL] run QARB-028B first")\n    d=json.loads(SRC.read_text(encoding="utf-8"))\n    hot={m for m in (d.get("mint_counts") or {}) if m!=WSOL}\n    from qseries_v2.oracle_strategy_intelligence.solana_money.qarb_clean_bot import persistent_profit_runtime as p\n    p.m.pd.MAX_PAIRS=p.MAX_PAIRS;state=p.m.prepare(Path(root))\n    covered=set(state.get("eps") or {});pairs={x.token for x in state.get("pairs",())}\n    rows=[{"mint":m,"mriya_tx_count":int(d["mint_counts"][m]),"qarb_priced":m in covered,"pump_meteora_pair":m in pairs} for m in sorted(hot)]\n    return {"mriya_non_wsol_hot_tokens":len(hot),"qarb_priced_tokens":len(covered),\n            "overlap":len(hot&covered),"missing":len(hot-covered),"rows":rows,\n            "venue_counts":d.get("venue_counts") or {},"execution_authority":False}\ndef run(root):\n    r=inspect(root);OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(r,indent=2,sort_keys=True),encoding="utf-8")\n    print("[QARB-029B] MRIYA REAL HOTSET VS QARB COVERAGE")\n    print("[COVERAGE] non_wsol_hot=%d qarb_priced=%d overlap=%d missing=%d"%(r["mriya_non_wsol_hot_tokens"],r["qarb_priced_tokens"],r["overlap"],r["missing"]))\n    print("[MRIYA_VENUES]",json.dumps(r["venue_counts"],sort_keys=True))\n    for x in sorted(r["rows"],key=lambda z:-z["mriya_tx_count"]):print("[HOTSET] token=%s tx=%d qarb_priced=%s pump_meteora=%s"%(x["mint"][:12],x["mriya_tx_count"],x["qarb_priced"],x["pump_meteora_pair"]))\n    print("[REPORT]",OUT);print("[MODE] READ_ONLY=True execution_authority=FALSE");return r\n',encoding="utf-8")
T=R/"test_qarb_029b_mriya_real_hotset_coverage_gap.py";T.write_text('import inspect,unittest\nfrom qseries_v2.oracle_strategy_intelligence.solana_money.qarb_clean_bot import qarb_029b_mriya_real_hotset_coverage_gap as q\nclass T(unittest.TestCase):\n    def test_wsol_excluded(self):self.assertIn("m!=WSOL",inspect.getsource(q.inspect))\n    def test_actual_runtime_compare(self):self.assertIn("p.m.prepare",inspect.getsource(q.inspect))\nif __name__=="__main__":unittest.main(verbosity=2)\n',encoding="utf-8")
U=R/"run_qarb_029b_mriya_real_hotset_coverage_gap.py";U.write_text("from pathlib import Path\nfrom qseries_v2.oracle_strategy_intelligence.solana_money.qarb_clean_bot.qarb_029b_mriya_real_hotset_coverage_gap import run\nif __name__=='__main__':run(Path.cwd())\n",encoding="utf-8")
for p in (M,T,U):py_compile.compile(str(p),doraise=True)
print("[PASS] QARB-029B installed")
print("[FIX] WSOL excluded; executor/CPI-derived mints compared to actual QARB live universe")
print("[MODE] READ_ONLY=True execution_authority=FALSE")
