from pathlib import Path
import ast,importlib,os,subprocess,sys,time
ROOT=Path.cwd().resolve();TARGET=ROOT/'qseries_v2/oracle_pre_settlement_coverage/opc_045_repeated_presettlement_observation_physical_proof.py';TEST=ROOT/'test_opc_045_repeated_presettlement_observation_physical_proof.py'
SOURCE='from pathlib import Path\nfrom qseries_v2.oracle_production_hardening.oph_019_postgresql_universal_ingestion_queue import connect\nfrom qseries_v2.oracle_intelligence_analytics_runtime.oiar_003_canonical_market_history_access_index import MARKET_ID_EXPRESSION,INDEX_NAME,_index_status\nfrom qseries_v2.oracle_pre_settlement_coverage.opc_023_rotating_full_universe_coverage_cycle import fetch_rotating_open_page\nfrom qseries_v2.oracle_pre_settlement_coverage.opc_022_rotating_universe_cursor_load_budget import CoverageLoadBudget\nOPC_045_BUILD_ID="OPC-045";OPC_045_REVISION="OPC_045_EXACT_OIAR003_INDEXED_REBUILD"\ndef physical_probe(root=None,max_markets=100,timeout_ms=15000):\n root=Path(root or Path.cwd()).resolve();st=_index_status(root)\n if not all(st):raise RuntimeError("OIAR-003 index not valid/ready/live")\n b=CoverageLoadBudget(page_limit=1000,max_snapshots_per_cycle=1000,cycle_sleep_seconds=0.0,lookback_hours=24.0,request_timeout_seconds=20.0);_,markets,_,raw=fetch_rotating_open_page(root,b);ids=tuple(dict.fromkeys(str(x.get("ticker") or "") for x in markets if x.get("ticker")))[:max_markets]\n sql=f"""SELECT wanted.market_id,h.sequence_number,h.observed_at FROM unnest(%s::text[]) AS wanted(market_id) LEFT JOIN LATERAL (SELECT sequence_number,observed_at FROM public.oracle_canonical_observations WHERE observation_type=\'market_snapshot\' AND ({MARKET_ID_EXPRESSION})=wanted.market_id ORDER BY sequence_number DESC LIMIT 3) h ON TRUE ORDER BY wanted.market_id,h.sequence_number DESC"""\n with connect(root,autocommit=False) as c:\n  with c.cursor() as cur:\n   cur.execute("SET TRANSACTION READ ONLY");cur.execute(f"SET LOCAL statement_timeout=\'{int(timeout_ms)}ms\'");cur.execute("EXPLAIN (FORMAT JSON) "+sql,(list(ids),));plan=cur.fetchone()[0];cur.execute(sql,(list(ids),));rows=cur.fetchall() or []\n  c.rollback()\n grouped={t:[] for t in ids}\n for t,seq,obs in rows:\n  if seq is not None:grouped[str(t)].append((seq,obs))\n repeated=sum(len(v)>=2 for v in grouped.values());observed=sum(bool(v) for v in grouped.values());pt=str(plan)\n if INDEX_NAME not in pt:raise RuntimeError("OPC-045 exact lookup did not use OIAR-003 index")\n return {"raw_page_markets":raw,"checked":len(ids),"markets_with_snapshot":observed,"markets_with_repeated_snapshots":repeated,"plan_uses_index":True,"index_name":INDEX_NAME,"sample":[(k,len(v)) for k,v in list(grouped.items())[:20]],"read_only":True,"execution_authority":False}\ndef verify_opc_045():return OPC_045_BUILD_ID=="OPC-045"\n';TEST_SOURCE='import unittest\nfrom qseries_v2.oracle_pre_settlement_coverage import opc_045_repeated_presettlement_observation_physical_proof as m\nclass T(unittest.TestCase):\n def test_physical(self):\n  self.assertTrue(m.verify_opc_045());x=m.physical_probe();self.assertTrue(x["plan_uses_index"]);self.assertGreater(x["checked"],0);self.assertTrue(x["read_only"]);self.assertFalse(x["execution_authority"])\nif __name__=="__main__":unittest.main(verbosity=2)\n'
def w(p,s):
 p.parent.mkdir(parents=True,exist_ok=True);t=p.with_name(p.name+f".{os.getpid()}.tmp");t.write_text(s,encoding="utf-8",newline="\n");os.replace(t,p)
def restore(p,b):
 if b is None:
  if p.exists():p.unlink()
 else:p.write_bytes(b)
def main():
 print("="*88);print(' OPC-045 REBUILD — EXACT OIAR-003 INDEXED HISTORY PROOF');print("="*88);print("[ROOT]",ROOT)
 bm=TARGET.read_bytes() if TARGET.exists() else None;bt=TEST.read_bytes() if TEST.exists() else None
 try:
  ast.parse(SOURCE);ast.parse(TEST_SOURCE);print("[PASS] payload syntax verified");w(TARGET,SOURCE);w(TEST,TEST_SOURCE);importlib.invalidate_caches()
  mn=TARGET.with_suffix("").relative_to(ROOT).as_posix().replace("/",".");m=importlib.import_module(mn);s=time.monotonic();r=m.physical_probe(ROOT);print("[PHYSICAL]",r,"elapsed_seconds=",round(time.monotonic()-s,3))
  subprocess.run([sys.executable,str(TEST)],cwd=str(ROOT),check=True,timeout=90)
 except Exception:
  restore(TARGET,bm);restore(TEST,bt);print("[ROLLBACK] failed; affected files restored");raise
 print("[DONE] INSTALLATION COMPLETE")
if __name__=="__main__":main()
