from pathlib import Path
import py_compile,importlib.util
R=Path.cwd();S=R/"qseries_v2/oracle_strategy_intelligence/solana_money/qarb_clean_bot"
for d in ():
    x=S/d
    if not x.is_file(): raise SystemExit("[FAIL] dependency missing: "+str(x))
M=S/"qarb_046_token_age_edge_decay.py";M.write_text('from __future__ import annotations\nimport json,statistics\nfrom collections import defaultdict\nfrom pathlib import Path\nLEDGER=Path("runtime_state/qseries/qarb_clean_bot/mriya_dynamic_age_outcomes.jsonl")\nOUT=Path("runtime_state/qseries/qarb_clean_bot/mriya_token_age_edge_decay.json")\nEXECUTION_AUTHORITY=False\nBUCKETS=((0,60,"0-60s"),(60,180,"1-3m"),(180,600,"3-10m"),(600,1800,"10-30m"),(1800,10**18,">30m"))\n\ndef age_bucket(x):\n    x=float(x)\n    for lo,hi,name in BUCKETS:\n        if lo<=x<hi:return name\n    return ">30m"\n\ndef append(row):\n    LEDGER.parent.mkdir(parents=True,exist_ok=True)\n    with LEDGER.open("a",encoding="utf-8") as f:f.write(json.dumps(row,sort_keys=True)+"\\n")\n\ndef analyze():\n    rows=[]\n    if LEDGER.is_file():\n        for line in LEDGER.read_text(encoding="utf-8").splitlines():\n            try:rows.append(json.loads(line))\n            except Exception:pass\n    g=defaultdict(list)\n    for x in rows:g[(age_bucket(x["token_age_seconds"]),float(x["horizon_seconds"]))].append(float(x["paper_net_sol"]))\n    out=[]\n    for (bucket,h),v in sorted(g.items()):\n        out.append({"age_bucket":bucket,"horizon_seconds":h,"episodes":len(v),"wins":sum(x>0 for x in v),\n                    "win_rate":sum(x>0 for x in v)/len(v),"net_sol":sum(v),"mean_sol":sum(v)/len(v),\n                    "median_sol":statistics.median(v),"worst_sol":min(v)})\n    payload={"rows":out,"raw_samples":len(rows),"execution_authority":False}\n    OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(payload,indent=2,sort_keys=True),encoding="utf-8")\n    return payload\n\ndef main():\n    print("[QARB-046] TOKEN-AGE / EDGE-DECAY MEASUREMENT")\n    r=analyze();print("[SAMPLES]",r["raw_samples"])\n    for x in r["rows"]:print("[AGE_DECAY] age=%s h=%gs n=%d w=%.0f%% pnl=%+.6f median=%+.6f worst=%+.6f"%(\n        x["age_bucket"],x["horizon_seconds"],x["episodes"],100*x["win_rate"],x["net_sol"],x["median_sol"],x["worst_sol"]))\n    print("[REPORT]",OUT);print("[MODE] READ_ONLY_ANALYTICS execution_authority=FALSE")\nif __name__=="__main__":main()\n',encoding="utf-8")
T=R/"test_qarb_046_token_age_edge_decay.py";T.write_text('import unittest\nfrom qseries_v2.oracle_strategy_intelligence.solana_money.qarb_clean_bot import qarb_046_token_age_edge_decay as q\nclass T(unittest.TestCase):\n    def test_buckets(self):\n        self.assertEqual(q.age_bucket(20),"0-60s");self.assertEqual(q.age_bucket(120),"1-3m")\n        self.assertEqual(q.age_bucket(400),"3-10m");self.assertEqual(q.age_bucket(1200),"10-30m")\n    def test_no_execution(self):self.assertFalse(q.EXECUTION_AUTHORITY)\nif __name__=="__main__":unittest.main(verbosity=2)\n',encoding="utf-8")
U=R/"run_qarb_046_token_age_edge_decay.py";U.write_text("from qseries_v2.oracle_strategy_intelligence.solana_money.qarb_clean_bot.qarb_046_token_age_edge_decay import main\nif __name__=='__main__':main()\n",encoding="utf-8")
for x in (M,T,U): py_compile.compile(str(x),doraise=True)
print("[PASS] qarb_046_token_age_edge_decay installed")
