from pathlib import Path
import py_compile
R=Path.cwd()
S=R/"qseries_v2/oracle_strategy_intelligence/solana_money/qarb_clean_bot"
if not S.is_dir(): raise SystemExit("[FAIL] clean-bot subsystem missing")
M=S/"qarb_057c_runtime_cutover_readiness_gate.py"; T=R/"test_qarb_057c_runtime_cutover_readiness_gate.py"; U=R/"run_qarb_057c_runtime_cutover_readiness_gate.py"
M.write_text('from __future__ import annotations\nimport json\nfrom pathlib import Path\n\nEXECUTION_AUTHORITY=False\nPAPER_ONLY=True\nA=Path("runtime_state/qseries/qarb_clean_bot/qarb_056a_damm_runtime_graph_extension.json")\nB=Path("runtime_state/qseries/qarb_clean_bot/qarb_057a_clmm_initialized_tick_decoder.json")\nC=Path("runtime_state/qseries/qarb_clean_bot/qarb_057b_orca_tick_array_pda_resolver.json")\nOUT=Path("runtime_state/qseries/qarb_clean_bot/qarb_057c_runtime_cutover_readiness_gate.json")\n\ndef load(root,p):\n    q=Path(root)/p\n    if not q.is_file():raise RuntimeError("MISSING:"+str(p))\n    return json.loads(q.read_text(encoding="utf-8"))\n\ndef build(root):\n    d=load(root,A);cl=load(root,B);oc=load(root,C)\n    gates={\n      "METEORA_DAMM_V2":bool(d.get("priced_live") and d.get("directed_edges")>=6),\n      "RAYDIUM_CLMM":bool(cl.get("directional_boundary_ready",0)>=2),\n      "ORCA_WHIRLPOOL":bool(oc.get("both_direction_sequences_ready",0)>=1)}\n    payload={"revision":"QARB_057C","gates":gates,\n      "pavement_complete_for_math":all(gates.values()),\n      "runtime_cutover_ready":False,\n      "remaining":["CLMM_LOCAL_SWAP_MATH","ORCA_LOCAL_SWAP_MATH","MERGE_NEW_ENDPOINTS_INTO_EXISTING_051D_GRAPH"],\n      "next":"QARB_058_LOCAL_SWAP_MATH_AND_RUNTIME_ENDPOINT_CUTOVER",\n      "execution_authority":False,"paper_only":True}\n    p=Path(root)/OUT;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(payload,indent=2,sort_keys=True),encoding="utf-8")\n    return payload\n\ndef main():\n    p=build(Path.cwd())\n    print("[QARB-057C] RUNTIME CUTOVER READINESS GATE")\n    print("[GATES] "+json.dumps(p["gates"],sort_keys=True))\n    print("[PAVEMENT_COMPLETE_FOR_MATH]",p["pavement_complete_for_math"])\n    print("[RUNTIME_CUTOVER_READY]",p["runtime_cutover_ready"])\n    print("[REMAINING] "+",".join(p["remaining"]))\n    print("[NEXT]",p["next"]);print("[REPORT]",OUT);print("[MODE] PAPER_ONLY=True execution_authority=FALSE")\nif __name__=="__main__":main()\n',encoding="utf-8")
T.write_text('import unittest\nfrom qseries_v2.oracle_strategy_intelligence.solana_money.qarb_clean_bot import qarb_057c_runtime_cutover_readiness_gate as q\nclass T(unittest.TestCase):\n    def test_mode(self): self.assertTrue(q.PAPER_ONLY); self.assertFalse(q.EXECUTION_AUTHORITY)\nif __name__=="__main__":unittest.main(verbosity=2)\n',encoding="utf-8")
U.write_text('from qseries_v2.oracle_strategy_intelligence.solana_money.qarb_clean_bot.qarb_057c_runtime_cutover_readiness_gate import main\nif __name__=="__main__":main()\n',encoding="utf-8")
for x in (M,T,U): py_compile.compile(str(x),doraise=True)
print('[PASS] QARB-057C runtime-cutover readiness gate installed')
print('[MODE] PAPER_ONLY=True execution_authority=FALSE')
