from pathlib import Path
import py_compile
R=Path.cwd()
S=R/"qseries_v2/oracle_strategy_intelligence/solana_money/qarb_clean_bot"
if not S.is_dir(): raise SystemExit("[FAIL] clean-bot subsystem missing")
M=S/"qarb_059b_provider_contract_prebinding_gate.py";T=R/"test_qarb_059b_provider_contract_prebinding_gate.py";U=R/"run_qarb_059b_provider_contract_prebinding_gate.py"
M.write_text('from __future__ import annotations\nimport inspect,json\nfrom pathlib import Path\nfrom qseries_v2.oracle_strategy_intelligence.solana_money.qarb_clean_bot.dex import raydium_clmm as rc\nfrom qseries_v2.oracle_strategy_intelligence.solana_money.qarb_clean_bot.dex import orca_whirlpool as ow\n\nEXECUTION_AUTHORITY=False\nPAPER_ONLY=True\nCLMM=Path("runtime_state/qseries/qarb_clean_bot/qarb_058a_clmm_local_swap_math.json")\nORCA=Path("runtime_state/qseries/qarb_clean_bot/qarb_058b_orca_local_swap_math.json")\nOUT=Path("runtime_state/qseries/qarb_clean_bot/qarb_059b_provider_contract_prebinding_gate.json")\n\ndef sig(x):\n    try:return str(inspect.signature(x))\n    except Exception:return None\n\ndef build(root):\n    root=Path(root)\n    cl=json.loads((root/CLMM).read_text(encoding="utf-8"))\n    oc=json.loads((root/ORCA).read_text(encoding="utf-8"))\n    rows={\n      "RAYDIUM_CLMM":{"poolstate":sig(rc.PoolState),"bind_local_quoter":sig(rc.bind_local_quoter),\n                      "quote_exact_in":sig(rc.quote_exact_in),"math_bound_pools":cl.get("math_bound_pools",0),\n                      "probe_complete_pools":cl.get("probe_complete_pools",0)},\n      "ORCA_WHIRLPOOL":{"poolstate":sig(ow.PoolState),"bind_local_quoter":sig(ow.bind_local_quoter),\n                        "quote_exact_in":sig(ow.quote_exact_in),"math_bound_pools":oc.get("math_bound_pools",0),\n                        "probe_complete_pools":oc.get("probe_complete_pools",0)}\n    }\n    for x in rows.values():\n        x["contract_ready"]=bool(x["poolstate"] and x["bind_local_quoter"] and x["quote_exact_in"]\n                                 and x["math_bound_pools"]>0 and x["probe_complete_pools"]>0)\n    payload={"revision":"QARB_059B","venues":rows,\n             "provider_contract_ready":all(x["contract_ready"] for x in rows.values()),\n             "provider_bound_live":False,\n             "next":"LIVE_SHADOW_VALIDATE_THEN_BIND_EXISTING_PROVIDER_CONTRACTS",\n             "execution_authority":False,"paper_only":True}\n    p=root/OUT;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(payload,indent=2,sort_keys=True),encoding="utf-8")\n    return payload\n\ndef main():\n    p=build(Path.cwd())\n    print("[QARB-059B] PROVIDER CONTRACT PREBINDING GATE")\n    for k,v in p["venues"].items():\n        print("[%s] contract_ready=%s math_bound=%d probe_complete=%d PoolState=%s bind=%s"%(\n            k,v["contract_ready"],v["math_bound_pools"],v["probe_complete_pools"],v["poolstate"],v["bind_local_quoter"]))\n    print("[PROVIDER_CONTRACT_READY]",p["provider_contract_ready"])\n    print("[PROVIDER_BOUND_LIVE]",p["provider_bound_live"])\n    print("[NEXT]",p["next"]);print("[REPORT]",OUT);print("[MODE] PAPER_ONLY=True execution_authority=FALSE")\nif __name__=="__main__":main()\n',encoding="utf-8")
T.write_text('import unittest\nfrom qseries_v2.oracle_strategy_intelligence.solana_money.qarb_clean_bot import qarb_059b_provider_contract_prebinding_gate as q\nclass T(unittest.TestCase):\n    def test_mode(self):self.assertTrue(q.PAPER_ONLY);self.assertFalse(q.EXECUTION_AUTHORITY)\n    def test_contracts(self):self.assertTrue(callable(q.rc.quote_exact_in));self.assertTrue(callable(q.ow.quote_exact_in))\nif __name__=="__main__":unittest.main(verbosity=2)\n',encoding="utf-8")
U.write_text('from qseries_v2.oracle_strategy_intelligence.solana_money.qarb_clean_bot.qarb_059b_provider_contract_prebinding_gate import main\nif __name__=="__main__":main()\n',encoding="utf-8")
for x in (M,T,U): py_compile.compile(str(x),doraise=True)
print('[PASS] QARB-059B provider-contract prebinding gate installed')
print('[RULE] no provider promoted live before quote validation')
print('[MODE] PAPER_ONLY=True execution_authority=FALSE')
