from pathlib import Path
import py_compile
R=Path.cwd();S=R/"qseries_v2/oracle_strategy_intelligence/solana_money/qarb_clean_bot"
D=S/"qarb_033_mriya_live_token_venue_matrix.py"
if not D.is_file():raise SystemExit("[FAIL] dependency missing: "+str(D))
M=S/"qarb_035_crossvenue_hot_token_priority_gate.py";M.write_text('from __future__ import annotations\nimport json\nfrom pathlib import Path\nSRC=Path("runtime_state/qseries/qarb_clean_bot/mriya_live_token_venue_matrix.json")\nOUT=Path("runtime_state/qseries/qarb_clean_bot/mriya_crossvenue_priority.json")\n\ndef rank():\n    if not SRC.is_file():raise SystemExit("[FAIL] run QARB-033 first")\n    d=json.loads(SRC.read_text(encoding="utf-8"));rows=[]\n    for x in d.get("rows",[]):\n        if not x.get("crossvenue_live"):continue\n        activity=0;venues=[]\n        for venue,items in x.get("venues",{}).items():\n            venues.append(venue)\n            activity+=max((int(i.get("updates",0)) for i in items),default=0)\n        preferred=int("PUMP_SWAP" in venues and "METEORA_DLMM" in venues)\n        ray=int(any(v.startswith("RAYDIUM") for v in venues))\n        score=preferred*1_000_000+ray*100_000+len(venues)*10_000+activity\n        rows.append({"mint":x["mint"],"venues":sorted(venues),"activity":activity,\n                     "preferred_pump_meteora":bool(preferred),"has_raydium":bool(ray),"score":score})\n    rows.sort(key=lambda z:(-z["score"],z["mint"]))\n    payload={"candidates":len(rows),"rows":rows,"execution_authority":False}\n    OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(payload,indent=2,sort_keys=True),encoding="utf-8")\n    return payload\n\ndef main():\n    print("[QARB-035] CROSS-VENUE HOT TOKEN PRIORITY GATE")\n    r=rank();print("[CANDIDATES]",r["candidates"])\n    for i,x in enumerate(r["rows"],1):\n        print("[PRIORITY] rank=%d token=%s venues=%s activity=%d pump_meteora=%s raydium=%s"%(\n            i,x["mint"][:12],x["venues"],x["activity"],x["preferred_pump_meteora"],x["has_raydium"]))\n    if r["rows"]:print("[NEXT_BIND_TARGET]",r["rows"][0]["mint"],r["rows"][0]["venues"])\n    print("[REPORT]",OUT);print("[MODE] READ_ONLY=True execution_authority=FALSE")\n',encoding="utf-8")
T=R/"test_qarb_035_crossvenue_hot_token_priority_gate.py";T.write_text('import unittest\nfrom qseries_v2.oracle_strategy_intelligence.solana_money.qarb_clean_bot import qarb_035_crossvenue_hot_token_priority_gate as q\nclass T(unittest.TestCase):\n    def test_paths(self):self.assertTrue(str(q.OUT).endswith("mriya_crossvenue_priority.json"))\nif __name__=="__main__":unittest.main(verbosity=2)\n',encoding="utf-8")
U=R/"run_qarb_035_crossvenue_hot_token_priority_gate.py";U.write_text("from qseries_v2.oracle_strategy_intelligence.solana_money.qarb_clean_bot.qarb_035_crossvenue_hot_token_priority_gate import main\nif __name__=='__main__':main()\n",encoding="utf-8")
for x in (M,T,U):py_compile.compile(str(x),doraise=True)
print("[PASS] QARB-035 installed")
print("[RANK] only tokens with physically live state on 2+ venues")
print("[MODE] READ_ONLY=True execution_authority=FALSE")
