from pathlib import Path
import ast,importlib,os,subprocess,sys,time
ROOT=Path.cwd().resolve();MOD=ROOT/"qseries_v2/oracle_intelligence_analytics_runtime/oiar_072_historical_recovery_semantics_boundary_proof.py";TEST=ROOT/"test_oiar_072_historical_recovery_semantics_boundary_proof.py";MODULE_SOURCE='from __future__ import annotations\nfrom pathlib import Path\nimport inspect,json\nfrom qseries_v2.oracle_interruption_recovery import oir_003_gap_state_backfill as oir3\nfrom qseries_v2.oracle_learning_feedback import olf_032_presettlement_price_recovery as olf32\nBUILD_ID="OIAR-072"\ndef physical_probe(root=None):\n root=Path(root or Path.cwd()).resolve();s3=inspect.getsource(oir3.recover_gap_market_states);s32=inspect.getsource(olf32.recover_presettlement_prices)\n artifact=root/"runtime_state"/getattr(oir3,"EVIDENCE_NAME","oracle_interruption_recovery_evidence.json");cached=None\n if artifact.is_file():\n  try:cached=json.loads(artifact.read_text(encoding="utf-8"))\n  except Exception:cached=None\n return {"oir_current_state_recovery_proven":("/markets/{ticker}" in s3 or "f\'/markets/{ticker}\'" in s3 or \'f"/markets/{ticker}"\' in s3),"oir_missing_tick_history_explicitly_unrecoverable":("unrecoverable" in s3.lower() and "history" in s3.lower()),"olf32_canonical_existing_history_only":("oracle_canonical_observations" in s32 and "market_snapshot" in s32),"olf32_post_settlement_exclusion_proven":("obs>settle" in s32.replace(" ","") or "obs > settle" in s32),"cached_oir_artifact_present":isinstance(cached,dict),"cached_oir_states_recovered":int((cached or {}).get("states_recovered",0) or 0),"historical_pre_settlement_fabrication_allowed":False,"read_only":True,"probability_enabled":False,"execution_authority":False}\ndef verify_oiar_072():return BUILD_ID=="OIAR-072" and callable(oir3.recover_gap_market_states) and callable(olf32.recover_presettlement_prices)\n';TEST_SOURCE='import unittest\nimport qseries_v2.oracle_intelligence_analytics_runtime.oiar_072_historical_recovery_semantics_boundary_proof as m\nclass T(unittest.TestCase):\n def test_contract(self):self.assertTrue(m.verify_oiar_072())\n def test_physical(self):\n  x=m.physical_probe();self.assertTrue(x["oir_current_state_recovery_proven"]);self.assertTrue(x["olf32_canonical_existing_history_only"]);self.assertFalse(x["historical_pre_settlement_fabrication_allowed"])\nif __name__=="__main__":\n print("="*88);print(" OIAR-072 CERTIFICATION TEST");print(" HISTORICAL RECOVERY SEMANTICS BOUNDARY PROOF");print("="*88)\n r=unittest.TextTestRunner(verbosity=2).run(unittest.defaultTestLoader.loadTestsFromTestCase(T))\n if not r.wasSuccessful():raise SystemExit(1)\n print("[PASS] recovery semantics boundary certified");print("[DONE] OIAR-072 CERTIFIED")\n'
def w(p,s):p.parent.mkdir(parents=True,exist_ok=True);t=p.with_name(p.name+f".{os.getpid()}.tmp");t.write_text(s,encoding="utf-8",newline="\n");os.replace(t,p)
def rr(p,b):
 if b is None:
  if p.exists():p.unlink()
 else:p.write_bytes(b)
def main():
 print("="*88);print(" OIAR-072 INSTALLER");print(" HISTORICAL RECOVERY SEMANTICS BOUNDARY PROOF");print("="*88);print("[ROOT]",ROOT)
 bm=MOD.read_bytes() if MOD.exists() else None;bt=TEST.read_bytes() if TEST.exists() else None
 try:
  ast.parse(MODULE_SOURCE);ast.parse(TEST_SOURCE);print("[PASS] installer payload syntax verified");w(MOD,MODULE_SOURCE);w(TEST,TEST_SOURCE);importlib.invalidate_caches();m=importlib.import_module("qseries_v2.oracle_intelligence_analytics_runtime.oiar_072_historical_recovery_semantics_boundary_proof");s=time.monotonic();x=m.physical_probe(ROOT);print("[PHYSICAL]",x,"elapsed_seconds=",round(time.monotonic()-s,3))
  if x["historical_pre_settlement_fabrication_allowed"]:raise RuntimeError("history fabrication invariant violated")
  subprocess.run([sys.executable,str(TEST)],cwd=str(ROOT),check=True,timeout=120)
 except Exception:
  rr(MOD,bm);rr(TEST,bt);print("[ROLLBACK] OIAR-072 failed; affected files restored");raise
 print("[PASS] current/final venue-state recovery distinguished from historical evidence");print("[PASS] probability_enabled=FALSE");print("[PASS] execution_authority=FALSE");print("[DONE] OIAR-072 INSTALLATION COMPLETE")
if __name__=="__main__":main()
