from pathlib import Path
import inspect,py_compile
R=Path.cwd();S=R/"qseries_v2/oracle_strategy_intelligence/solana_money/qarb_clean_bot"
for d in (S/"qarb_037_mriya_priority_pair_hydration.py",S/"qarb_026h_fresh_crossvenue_paper_gate.py",S/"persistent_profit_runtime.py"):
    if not d.is_file():raise SystemExit("[FAIL] dependency missing: "+str(d))
from qseries_v2.oracle_strategy_intelligence.solana_money.qarb_clean_bot import persistent_profit_runtime as p
src=inspect.getsource(p.serve)
if "state=m.prepare(root)" not in src:raise SystemExit("[FAIL] persistent serve prepare contract changed")
M=S/"qarb_038_mriya_hotset_fresh_paper_runtime.py";M.write_text('from __future__ import annotations\nimport asyncio,json\nfrom pathlib import Path\nfrom qseries_v2.oracle_strategy_intelligence.solana_money.qarb_clean_bot import persistent_profit_runtime as p\nfrom qseries_v2.oracle_strategy_intelligence.solana_money.qarb_clean_bot import qarb_026g_token_freshness_profit_audit as qg\nfrom qseries_v2.oracle_strategy_intelligence.solana_money.qarb_clean_bot import qarb_026h_fresh_crossvenue_paper_gate as qh\nfrom qseries_v2.oracle_strategy_intelligence.solana_money.qarb_clean_bot import qarb_037_mriya_priority_pair_hydration as h\n\nEXECUTION_AUTHORITY=False\nPAPER_ONLY=True\n_ORIG_PREPARE_PAIRS=p.m.pd.prepare_pairs\n\ndef priority_prepare_pairs(root):\n    pairs,landing,_=h.hydrate(Path(root))\n    print("[MRIYA_HOTSET] hydrated_priority_pairs=%d tokens=%s"%(\n        len(pairs),[x.token[:12] for x in pairs]),flush=True)\n    return pairs,landing\n\ndef install():\n    qg.VENUE_TS.clear()\n    p.m.pd.prepare_pairs=priority_prepare_pairs\n    p.m.pd.apply_account_event=qg.tracked_apply\n    p.SimulationLane=qh.FreshOnlyPaperLane\n    return p\n\ndef main(argv=None):\n    import argparse\n    ap=argparse.ArgumentParser();ap.add_argument("--seconds",type=float,default=None);a=ap.parse_args(argv)\n    runtime=install()\n    print("[QARB-038] MRIYA-HOTSET FRESH PAPER PROFIT RUNTIME",flush=True)\n    print("[ENGINE] original persistent_profit_runtime.serve unchanged",flush=True)\n    print("[UNIVERSE] QARB-036 exact top PumpSwap/Meteora bindings",flush=True)\n    print("[PAPER_GATE] both venues live-observed and <=750ms old",flush=True)\n    print("[HORIZONS] 2s,5s,15s,30s,60s,90s",flush=True)\n    print("[MODE] PAPER_ONLY=True execution_authority=FALSE",flush=True)\n    return asyncio.run(runtime.serve(Path.cwd(),a.seconds))\nif __name__=="__main__":main()\n',encoding="utf-8")
T=R/"test_qarb_038_mriya_hotset_fresh_paper_runtime.py";T.write_text('import inspect,unittest\nfrom qseries_v2.oracle_strategy_intelligence.solana_money.qarb_clean_bot import qarb_038_mriya_hotset_fresh_paper_runtime as q\nclass T(unittest.TestCase):\n    def test_original_serve(self):\n        s=inspect.getsource(q);self.assertNotIn("async def serve(",s);self.assertIn("runtime.serve(Path.cwd()",s)\n    def test_priority_prepare(self):\n        s=inspect.getsource(q.install);self.assertIn("p.m.pd.prepare_pairs=priority_prepare_pairs",s)\n    def test_fresh_lane(self):\n        s=inspect.getsource(q.install);self.assertIn("FreshOnlyPaperLane",s);self.assertIn("tracked_apply",s)\n    def test_read_only(self):\n        self.assertTrue(q.PAPER_ONLY);self.assertFalse(q.EXECUTION_AUTHORITY)\nif __name__=="__main__":unittest.main(verbosity=2)\n',encoding="utf-8")
U=R/"run_qarb_038_mriya_hotset_fresh_paper_runtime.py";U.write_text("from qseries_v2.oracle_strategy_intelligence.solana_money.qarb_clean_bot.qarb_038_mriya_hotset_fresh_paper_runtime import main\nif __name__=='__main__':main()\n",encoding="utf-8")
for x in (M,T,U):py_compile.compile(str(x),doraise=True)
print("[PASS] QARB-038 installed")
print("[ENGINE] persistent_profit_runtime.serve unchanged")
print("[UNIVERSE] exact Mriya hot PumpSwap/Meteora bindings replace old discovery at startup")
print("[PAPER] fresh-only 2/5/15/30/60/90s forward PNL")
print("[MODE] PAPER_ONLY=True execution_authority=FALSE")
