from pathlib import Path
import py_compile
R=Path.cwd()
S=R/"qseries_v2/oracle_strategy_intelligence/solana_money/qarb_clean_bot"
if not S.is_dir(): raise SystemExit("[FAIL] clean-bot subsystem missing")
M=S/"qarb_052b6_clmm_live_account_state.py"
T=R/"test_qarb_052b6_clmm_live_account_state.py"
U=R/"run_qarb_052b6_clmm_live_account_state.py"
M.write_text('from __future__ import annotations\nimport base64,json,time\nfrom pathlib import Path\nfrom qseries_v2.oracle_strategy_intelligence.solana_money.native_atomic_money_machine import core as c\n\nEXECUTION_AUTHORITY=False\nPAPER_ONLY=True\nMAX_AGE_MS=750.0\nSRC=Path("runtime_state/qseries/qarb_clean_bot/qarb_052b5_clmm_exact_descriptor_pavement.json")\nOUT=Path("runtime_state/qseries/qarb_clean_bot/qarb_052b6_clmm_live_account_state.json")\n\ndef load_desc(root):\n    p=Path(root)/SRC\n    if not p.is_file(): raise RuntimeError("QARB_052B5_ARTIFACT_MISSING")\n    o=json.loads(p.read_text(encoding="utf-8"))\n    return list(o.get("descriptors") or [])\n\ndef materialize(root):\n    rows=[];errors=[]\n    for d in load_desc(root):\n        accounts=list(d.get("watched_accounts") or [])\n        live=[]\n        for a in accounts:\n            addr=a.get("pubkey") if isinstance(a,dict) else a\n            if not isinstance(addr,str) or not addr: continue\n            try:\n                raw,slot=c.account(addr)\n                live.append({"address":addr,"bytes":len(raw),"slot":slot})\n            except Exception as e:\n                errors.append({"pool":d.get("pool"),"address":addr,"error":type(e).__name__+":"+str(e)})\n        rows.append({"pool":d.get("pool"),"token_a":d.get("token_a"),"token_b":d.get("token_b"),\n                     "account_count":len(accounts),"live_accounts":live,\n                     "live_account_count":len(live),"observed_ns":time.perf_counter_ns()})\n    return rows,errors\n\ndef main():\n    root=Path.cwd();rows,errors=materialize(root)\n    payload={"revision":"QARB_052B6","pool_count":len(rows),\n             "live_pool_count":sum(1 for r in rows if r["live_account_count"]>0),\n             "rows":rows,"errors":errors[:30],"local_quote_bound":False,\n             "next_boundary":"RAYDIUM_CLMM_LOCAL_MATH_FROM_LIVE_POOL_TICK_STATE",\n             "execution_authority":False}\n    p=root/OUT;p.parent.mkdir(parents=True,exist_ok=True)\n    p.write_text(json.dumps(payload,indent=2,sort_keys=True),encoding="utf-8")\n    print("[QARB-052B6] RAYDIUM CLMM LIVE ACCOUNT STATE")\n    print("[CLMM_POOLS]",payload["pool_count"])\n    print("[CLMM_LIVE_POOLS]",payload["live_pool_count"])\n    for r in rows: print("[CLMM_LIVE_STATE]",str(r["pool"])[:12],"accounts=%d/%d"%(r["live_account_count"],r["account_count"]))\n    print("[LOCAL_QUOTE_BOUND]",False)\n    print("[NEXT]",payload["next_boundary"])\n    print("[REPORT]",OUT)\n    print("[MODE] PAPER_ONLY=True execution_authority=FALSE")\n',encoding="utf-8")
T.write_text('import unittest\nfrom qseries_v2.oracle_strategy_intelligence.solana_money.qarb_clean_bot import qarb_052b6_clmm_live_account_state as q\nclass T(unittest.TestCase):\n    def test_mode(self): self.assertTrue(q.PAPER_ONLY); self.assertFalse(q.EXECUTION_AUTHORITY)\n    def test_freshness(self): self.assertEqual(q.MAX_AGE_MS,750.0)\nif __name__=="__main__": unittest.main(verbosity=2)\n',encoding="utf-8")
U.write_text('from qseries_v2.oracle_strategy_intelligence.solana_money.qarb_clean_bot.qarb_052b6_clmm_live_account_state import main\nif __name__=="__main__": main()\n',encoding="utf-8")
for x in (M,T,U): py_compile.compile(str(x),doraise=True)
print('[PASS] QARB-052B6 CLMM live-account state materializer installed')
print('[REUSE] QARB-052B5 exact pools/mints/accounts')
print('[NO_FAKE_QUOTE] this build materializes physical live state only')
print('[MODE] PAPER_ONLY=True execution_authority=FALSE')
