import unittest
class T(unittest.TestCase):
 def test_audit(self):
  print("[IMPORTS]",[{'module': '__future__', 'names': ['annotations'], 'level': 0}, {'module': None, 'names': ['asyncio', 'json', 'time'], 'level': 0}, {'module': 'pathlib', 'names': ['Path'], 'level': 0}, {'module': 'qseries_v2.oracle_adapters.independent.oad_148_solana_mainnet_chain_state_acquisition', 'names': ['_rpc'], 'level': 0}, {'module': 'qseries_v2.oracle_strategy_intelligence.solana_launch_surveillance.suls_076_birth_log_notification_filter', 'names': ['is_birth'], 'level': 0}, {'module': 'qseries_v2.oracle_strategy_intelligence.solana_launch_surveillance.suls_080_event_driven_lifecycle_bridge', 'names': ['run'], 'level': 0}, {'module': None, 'names': ['websockets'], 'level': 0}])
  print("[SERVE]")
  print('0028: async def serve(root,max_notifications=None,max_seconds=None):\n0029:  import websockets\n0030:  base=root/"runtime_state/solana_opportunities/launch_surveillance"\n0031:  c=json.loads((base/"confirmed_logs_subscription_contract.json").read_text(encoding="utf-8"))\n0032:  stop=root/"runtime_state/solana_intelligence/STOP_OSI_LIVE"\n0033:  cp=base/"persistent_event_driven_runtime_status.json"\n0034:  seen=set();notes=0;births=0;started=time.time()\n0035:  async with websockets.connect(c["ws_url"],ping_interval=20,ping_timeout=20,close_timeout=3,max_size=8_000_000) as ws:\n0036:   for sub in c["subscriptions"]:await ws.send(json.dumps(sub))\n0037:   acks=0\n0038:   while not stop.exists():\n0039:    if max_notifications is not None and notes>=int(max_notifications):break\n0040:    if max_seconds is not None and time.time()-started>=float(max_seconds):break\n0041:    try:raw=await asyncio.wait_for(ws.recv(),timeout=1.0)\n0042:    except asyncio.TimeoutError:\n0043:     continue\n0044:    msg=json.loads(raw)\n0045:    if "id" in msg and "result" in msg:\n0046:     acks+=1;continue\n0047:    if msg.get("method")!="logsNotification":continue\n0048:    notes+=1;received=time.time()\n0049:    result=((msg.get("params") or {}).get("result") or {})\n0050:    v=result.get("value") or {};ctx=result.get("context") or {}\n0051:    sig=v.get("signature");logs=v.get("logs") or []\n0052:    if v.get("err") is None and sig and sig not in seen and is_birth(logs):')
  print("[PASS] USLS-014F exact subscription config provenance audit")
  print("[SCOPE] diagnostic only; production runtime unchanged")
  print("[PASS] execution_authority=FALSE")
if __name__=="__main__":unittest.main()
