"""
Oracle live read-only acquisition subsystem.
"""

from .oracle_live_read_only_acquisition_runtime import (
    AcquisitionBatchRecord,
    AcquisitionContractError,
    AcquisitionInvariantError,
    AcquisitionObservationRecord,
    ApprovedReadOnlySourceAdapter,
    ApprovedSourceAdapterRegistration,
    CanonicalObservation,
    CanonicalObservationRouterFailure,
    DeduplicationEvidence,
    ObservationRoutingEvidence,
    OracleLiveReadOnlyAcquisitionRuntime,
    RateControlEvidence,
    RawSourceObservation,
    SourceAdapterFailure,
    SourceHealthEvidence,
    UnapprovedSourceAdapterError,
)

from .oracle_acquisition_source_control_engine import (
    OracleAcquisitionSourceControlEngine,
    RateControlPolicy,
    RateWindowObservation,
    SourceControlContractError,
    SourceControlDecisionRecord,
    SourceControlInvariantError,
    SourceControlPolicyError,
    SourceHealthObservation,
    SourceHealthPolicy,
)

from .oracle_acquisition_deduplication_ledger import (
    CanonicalDeduplicationLedgerEntry,
    DeduplicationLedgerContractError,
    DeduplicationLedgerInvariantError,
    DeduplicationLedgerSnapshot,
    DeduplicationLedgerSnapshotError,
    OracleAcquisitionDeduplicationLedger,
)

from .oracle_canonical_market_identity_venue_resolution_engine import (
    ApprovedVenueRegistration,
    CanonicalMarketIdentity,
    CanonicalMarketVenueRecord,
    MarketIdentityContractError,
    OracleCanonicalMarketIdentityVenueResolutionEngine,
    SourceMarketIdentityEvidence,
    VenueResolutionError,
    VenueResolutionInvariantError,
    VerifiedVenueResolution,
)

from .oracle_canonical_opportunity_validity_expiration_engine import (
    CanonicalOpportunityValidityEvidence,
    OpportunityValidityContractError,
    OpportunityValidityInvariantError,
    OpportunityValidityRequest,
    OracleCanonicalOpportunityValidityExpirationEngine,
)

from .oracle_canonical_cross_venue_opportunity_comparison_engine import (
    ComparisonScoringPolicy,
    CrossVenueOpportunityCandidate,
    CrossVenueOpportunityComparisonResult,
    OpportunityComparabilityError,
    OpportunityComparisonContractError,
    OpportunityComparisonInvariantError,
    OracleCanonicalCrossVenueOpportunityComparisonEngine,
    RankedCrossVenueOpportunity,
)

from .oracle_canonical_opportunity_alert_record_engine import (
    CanonicalOpportunityAlertRecord,
    OpportunityAlertContractError,
    OpportunityAlertInvariantError,
    OpportunityAlertSelectionError,
    OracleCanonicalOpportunityAlertRecordEngine,
)

from .oracle_canonical_observation_persistence_ledger import (
    CanonicalObservationPersistenceEntry,
    CanonicalObservationPersistenceSnapshot,
    ObservationPersistenceConflictError,
    ObservationPersistenceContractError,
    ObservationPersistenceInvariantError,
    ObservationPersistenceSnapshotError,
    OracleCanonicalObservationPersistenceLedger,
)

from .oracle_canonical_observation_persistence_router import (
    CanonicalObservationPersistenceRoutingRecord,
    OracleCanonicalObservationPersistenceRouter,
    PersistenceRoutingContractError,
    PersistenceRoutingFailure,
    PersistenceRoutingInvariantError,
)

from .oracle_controlled_acquisition_cycle_orchestrator import (
    AcquisitionCycleContractError,
    AcquisitionCycleInvariantError,
    AcquisitionCycleReconciliationError,
    ControlledAcquisitionCycleRecord,
    OracleControlledAcquisitionCycleOrchestrator,
)

from .oracle_canonical_persistence_backend_contract import (
    CanonicalPersistenceAppendRequest,
    CanonicalPersistenceAppendResult,
    CanonicalPersistenceQueryRequest,
    CanonicalPersistenceSnapshotCheckpoint,
    OracleCanonicalPersistenceBackend,
    OraclePersistenceBackendContractValidator,
    PersistenceBackendCapabilityError,
    PersistenceBackendCapabilityRecord,
    PersistenceBackendConflictError,
    PersistenceBackendContractError,
    PersistenceBackendHealthRecord,
    PersistenceBackendInvariantError,
    REQUIRED_BACKEND_CAPABILITIES,
)

__all__ = [
    "AcquisitionBatchRecord",
    "AcquisitionContractError",
    "AcquisitionInvariantError",
    "AcquisitionObservationRecord",
    "ApprovedReadOnlySourceAdapter",
    "ApprovedSourceAdapterRegistration",
    "CanonicalObservation",
    "CanonicalObservationRouterFailure",
    "DeduplicationEvidence",
    "ObservationRoutingEvidence",
    "OracleLiveReadOnlyAcquisitionRuntime",
    "RateControlEvidence",
    "RawSourceObservation",
    "SourceAdapterFailure",
    "SourceHealthEvidence",
    "UnapprovedSourceAdapterError",
    "OracleAcquisitionSourceControlEngine",
    "RateControlPolicy",
    "RateWindowObservation",
    "SourceControlContractError",
    "SourceControlDecisionRecord",
    "SourceControlInvariantError",
    "SourceControlPolicyError",
    "SourceHealthObservation",
    "SourceHealthPolicy",
    "CanonicalDeduplicationLedgerEntry",
    "DeduplicationLedgerContractError",
    "DeduplicationLedgerInvariantError",
    "DeduplicationLedgerSnapshot",
    "DeduplicationLedgerSnapshotError",
    "OracleAcquisitionDeduplicationLedger",
    "ApprovedVenueRegistration",
    "CanonicalMarketIdentity",
    "CanonicalMarketVenueRecord",
    "MarketIdentityContractError",
    "OracleCanonicalMarketIdentityVenueResolutionEngine",
    "SourceMarketIdentityEvidence",
    "VenueResolutionError",
    "VenueResolutionInvariantError",
    "VerifiedVenueResolution",
    "CanonicalOpportunityValidityEvidence",
    "OpportunityValidityContractError",
    "OpportunityValidityInvariantError",
    "OpportunityValidityRequest",
    "OracleCanonicalOpportunityValidityExpirationEngine",
    "ComparisonScoringPolicy",
    "CrossVenueOpportunityCandidate",
    "CrossVenueOpportunityComparisonResult",
    "OpportunityComparabilityError",
    "OpportunityComparisonContractError",
    "OpportunityComparisonInvariantError",
    "OracleCanonicalCrossVenueOpportunityComparisonEngine",
    "RankedCrossVenueOpportunity",
    "CanonicalOpportunityAlertRecord",
    "OpportunityAlertContractError",
    "OpportunityAlertInvariantError",
    "OpportunityAlertSelectionError",
    "OracleCanonicalOpportunityAlertRecordEngine",
    "CanonicalObservationPersistenceEntry",
    "CanonicalObservationPersistenceSnapshot",
    "ObservationPersistenceConflictError",
    "ObservationPersistenceContractError",
    "ObservationPersistenceInvariantError",
    "ObservationPersistenceSnapshotError",
    "OracleCanonicalObservationPersistenceLedger",
    "CanonicalObservationPersistenceRoutingRecord",
    "OracleCanonicalObservationPersistenceRouter",
    "PersistenceRoutingContractError",
    "PersistenceRoutingFailure",
    "PersistenceRoutingInvariantError",
    "AcquisitionCycleContractError",
    "AcquisitionCycleInvariantError",
    "AcquisitionCycleReconciliationError",
    "ControlledAcquisitionCycleRecord",
    "OracleControlledAcquisitionCycleOrchestrator",
    "CanonicalPersistenceAppendRequest",
    "CanonicalPersistenceAppendResult",
    "CanonicalPersistenceQueryRequest",
    "CanonicalPersistenceSnapshotCheckpoint",
    "OracleCanonicalPersistenceBackend",
    "OraclePersistenceBackendContractValidator",
    "PersistenceBackendCapabilityError",
    "PersistenceBackendCapabilityRecord",
    "PersistenceBackendConflictError",
    "PersistenceBackendContractError",
    "PersistenceBackendHealthRecord",
    "PersistenceBackendInvariantError",
    "REQUIRED_BACKEND_CAPABILITIES",
    "POSTGRESQL_CANONICAL_BACKEND_ID",
    "POSTGRESQL_CANONICAL_BACKEND_TYPE",
    "POSTGRESQL_CANONICAL_GENESIS_CHAIN_HASH",
    "OraclePostgreSQLCanonicalObservationPersistenceBackend",
    "PostgreSQLPersistenceBackendError",
    "PostgreSQLPersistenceIntegrityError",
    "PostgreSQLPersistenceSchemaError",
    "OraclePostgreSQLSecureConfigurationConnectionFactory",
    "PostgreSQLConfigurationContractError",
    "PostgreSQLConfigurationInvariantError",
    "PostgreSQLConnectionFactoryError",
    "PostgreSQLConnectionFactoryEvidence",
    "PostgreSQLDriverLoadError",
    "PostgreSQLSecretBoundaryError",
    "PostgreSQLSecretEnvironmentContract",
    "SUPPORTED_SSL_MODES",
    "SanitizedPostgreSQLConfiguration",
    "OraclePostgreSQLProductionBootstrapMigrationGate",
    "PostgreSQLBootstrapCompatibilityError",
    "PostgreSQLBootstrapContractError",
    "PostgreSQLBootstrapInvariantError",
    "PostgreSQLProductionBootstrapRecord",
    "OraclePostgreSQLCanonicalObservationPersistenceRouter",
    "PostgreSQLCanonicalObservationPersistenceRoutingRecord",
    "PostgreSQLPersistenceRoutingContractError",
    "PostgreSQLPersistenceRoutingFailure",
    "PostgreSQLPersistenceRoutingInvariantError",
    "KALSHI_SHADOW_ADAPTER_ID",
    "KALSHI_SHADOW_ALERTS_ALLOWED",
    "KALSHI_SHADOW_MAX_PAGE_LIMIT",
    "KALSHI_PUBLIC_MARKETS_PATH",
    "KALSHI_PRODUCTION_BASE_URL",
    "KALSHI_SHADOW_Q_SERIES_INTAKE_ALLOWED",
    "KALSHI_SHADOW_MODE",
    "KALSHI_MARKET_DATA_SOURCE_ID",
    "KALSHI_SUPPORTED_MARKET_STATUSES",
    "KALSHI_VENUE_ID",
    "KalshiPublicMarketSourceHealthEvidence",
    "KalshiShadowAcquisitionEvidence",
    "KalshiShadowAdapterContractError",
    "KalshiShadowAdapterInvariantError",
    "KalshiShadowAdapterSourceError",
    "OracleKalshiPublicMarketShadowSourceAdapter",
    "raw_observation_canonical_dict",
    "raw_observation_stable_hash",
    "OraclePostgreSQLShadowAcquisitionCycleOrchestrator",
    "PostgreSQLShadowAcquisitionCycleRecord",
    "PostgreSQLShadowCycleCompatibilityError",
    "PostgreSQLShadowCycleContractError",
    "PostgreSQLShadowCycleInvariantError",
    "PostgreSQLShadowCycleReconciliationError",
    "KalshiLiveReadReadinessContractError",
    "KalshiLiveReadReadinessFailure",
    "KalshiLiveReadReadinessInvariantError",
    "KalshiLiveReadReadinessRecord",
    "OracleKalshiLiveReadReadinessGate",
    "FINAL_APPROVAL_REASON_CODE",
    "HEALTH_APPROVAL_REASON_CODES",
    "RATE_APPROVAL_REASON_CODES",
    "SHADOW_POLLING_BLOCKED_STATUS",
    "SHADOW_POLLING_ELIGIBLE_STATUS",
    "SHADOW_POLLING_SUSPENDED_STATUS",
    "SHADOW_POLLING_WAITING_STATUS",
    "OracleShadowPollingPolicyCadenceEngine",
    "ShadowPollingDecision",
    "ShadowPollingPolicy",
    "ShadowPollingPolicyCompatibilityError",
    "ShadowPollingPolicyContractError",
    "ShadowPollingPolicyInvariantError",
    "ShadowPollingState",
    "HANDOFF_STATUS_PUBLISHED",
    "ORACLE_SERVICE_ROLE",
    "Q_SERIES_SERVICE_ROLE",
    "CanonicalIntelligenceHandoffContractError",
    "CanonicalIntelligenceHandoffInvariantError",
    "CanonicalIntelligenceHandoffRecord",
    "OracleQSeriesServiceIsolationContract",
    "OracleServiceIsolationContractError",
    "REQUIRED_CYCLE_RUNNER_ENGINE_ID",
    "TICK_COMPLETED_STATUS",
    "TICK_FAILED_STATUS",
    "TICK_NOOP_STATUS",
    "OracleControlledShadowCollectionSchedulerTick",
    "ShadowCollectionSchedulerTickCompatibilityError",
    "ShadowCollectionSchedulerTickContractError",
    "ShadowCollectionSchedulerTickInvariantError",
    "ShadowCollectionSchedulerTickRecord",
    "ShadowCycleRunnerBinding",
]


from .oracle_postgresql_canonical_observation_persistence_backend import (
    BACKEND_ID as POSTGRESQL_CANONICAL_BACKEND_ID,
    BACKEND_TYPE as POSTGRESQL_CANONICAL_BACKEND_TYPE,
    GENESIS_CHAIN_HASH as POSTGRESQL_CANONICAL_GENESIS_CHAIN_HASH,
    OraclePostgreSQLCanonicalObservationPersistenceBackend,
    PostgreSQLPersistenceBackendError,
    PostgreSQLPersistenceIntegrityError,
    PostgreSQLPersistenceSchemaError,
)


from .oracle_postgresql_secure_configuration_connection_factory import (
    OraclePostgreSQLSecureConfigurationConnectionFactory,
    PostgreSQLConfigurationContractError,
    PostgreSQLConfigurationInvariantError,
    PostgreSQLConnectionFactoryError,
    PostgreSQLConnectionFactoryEvidence,
    PostgreSQLDriverLoadError,
    PostgreSQLSecretBoundaryError,
    PostgreSQLSecretEnvironmentContract,
    SUPPORTED_SSL_MODES,
    SanitizedPostgreSQLConfiguration,
)


from .oracle_postgresql_production_bootstrap_migration_gate import (
    OraclePostgreSQLProductionBootstrapMigrationGate,
    PostgreSQLBootstrapCompatibilityError,
    PostgreSQLBootstrapContractError,
    PostgreSQLBootstrapInvariantError,
    PostgreSQLProductionBootstrapRecord,
)


from .oracle_postgresql_canonical_observation_persistence_router import (
    OraclePostgreSQLCanonicalObservationPersistenceRouter,
    PostgreSQLCanonicalObservationPersistenceRoutingRecord,
    PostgreSQLPersistenceRoutingContractError,
    PostgreSQLPersistenceRoutingFailure,
    PostgreSQLPersistenceRoutingInvariantError,
)


from .oracle_kalshi_public_market_shadow_source_adapter import (
    ADAPTER_ID as KALSHI_SHADOW_ADAPTER_ID,
    ALERTS_ALLOWED as KALSHI_SHADOW_ALERTS_ALLOWED,
    MAX_PAGE_LIMIT as KALSHI_SHADOW_MAX_PAGE_LIMIT,
    MARKETS_PATH as KALSHI_PUBLIC_MARKETS_PATH,
    PRODUCTION_BASE_URL as KALSHI_PRODUCTION_BASE_URL,
    Q_SERIES_INTAKE_ALLOWED as KALSHI_SHADOW_Q_SERIES_INTAKE_ALLOWED,
    SHADOW_MODE as KALSHI_SHADOW_MODE,
    SOURCE_ID as KALSHI_MARKET_DATA_SOURCE_ID,
    SUPPORTED_MARKET_STATUSES as KALSHI_SUPPORTED_MARKET_STATUSES,
    VENUE_ID as KALSHI_VENUE_ID,
    KalshiPublicMarketSourceHealthEvidence,
    KalshiShadowAcquisitionEvidence,
    KalshiShadowAdapterContractError,
    KalshiShadowAdapterInvariantError,
    KalshiShadowAdapterSourceError,
    OracleKalshiPublicMarketShadowSourceAdapter,
    raw_observation_canonical_dict,
    raw_observation_stable_hash,
)


from .oracle_postgresql_shadow_acquisition_cycle_orchestrator import (
    OraclePostgreSQLShadowAcquisitionCycleOrchestrator,
    PostgreSQLShadowAcquisitionCycleRecord,
    PostgreSQLShadowCycleCompatibilityError,
    PostgreSQLShadowCycleContractError,
    PostgreSQLShadowCycleInvariantError,
    PostgreSQLShadowCycleReconciliationError,
)


from .oracle_kalshi_live_read_readiness_gate import (
    FINAL_APPROVAL_REASON_CODE,
    HEALTH_APPROVAL_REASON_CODES,
    RATE_APPROVAL_REASON_CODES,
    KalshiLiveReadReadinessContractError,
    KalshiLiveReadReadinessFailure,
    KalshiLiveReadReadinessInvariantError,
    KalshiLiveReadReadinessRecord,
    OracleKalshiLiveReadReadinessGate,
)


from .oracle_shadow_polling_policy_cadence_engine import (
    BLOCKED_STATUS as SHADOW_POLLING_BLOCKED_STATUS,
    ELIGIBLE_STATUS as SHADOW_POLLING_ELIGIBLE_STATUS,
    SUSPENDED_STATUS as SHADOW_POLLING_SUSPENDED_STATUS,
    WAITING_STATUS as SHADOW_POLLING_WAITING_STATUS,
    OracleShadowPollingPolicyCadenceEngine,
    ShadowPollingDecision,
    ShadowPollingPolicy,
    ShadowPollingPolicyCompatibilityError,
    ShadowPollingPolicyContractError,
    ShadowPollingPolicyInvariantError,
    ShadowPollingState,
)


from .oracle_service_isolation_canonical_intelligence_handoff_contract import (
    HANDOFF_STATUS_PUBLISHED,
    ORACLE_SERVICE_ROLE,
    Q_SERIES_SERVICE_ROLE,
    CanonicalIntelligenceHandoffContractError,
    CanonicalIntelligenceHandoffInvariantError,
    CanonicalIntelligenceHandoffRecord,
    OracleQSeriesServiceIsolationContract,
    OracleServiceIsolationContractError,
)


from .oracle_controlled_shadow_collection_scheduler_tick import (
    REQUIRED_CYCLE_RUNNER_ENGINE_ID,
    TICK_COMPLETED_STATUS,
    TICK_FAILED_STATUS,
    TICK_NOOP_STATUS,
    OracleControlledShadowCollectionSchedulerTick,
    ShadowCollectionSchedulerTickCompatibilityError,
    ShadowCollectionSchedulerTickContractError,
    ShadowCollectionSchedulerTickInvariantError,
    ShadowCollectionSchedulerTickRecord,
    ShadowCycleRunnerBinding,
)
